version: '3'

volumes:
    prometheus_data: {}
    grafana_data: {}


networks:
    monitor-net:
        driver: bridge

services:
    prometheus:
        image: prom/prometheus
        container_name: prometheus
        volumes:
            - ./prometheus:/etc/prometheus
            - prometheus_data:/prometheus
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
        restart: unless-stopped
        ports:
            - "9090:9090"
        networks:
            - monitor-net


    grafana:
        image: grafana/grafana
        container_name: grafana
        volumes:
            - grafana_data:/var/lib/grafana
            - ./grafana/provisioning:/etc/grafana/provisioning
        environment:
            - GF_SECURITY_ADMIN_USER=admin
            - GF_SECURITY_ADMIN_PASSWORD=admin
            - GF_USERS_ALLOW_SIGN_UP=false
        restart: unless-stopped
        ports:
            - "3000:3000"
        networks:
            - monitor-net
